### ISSUE TITLE
Hi Jeff

### ISSUE THREAD

**Issue by aloess** [programmervsworld/Sling_Tutorial#1]
Hi Jeff, nice to meet you, i followed all your steps in the videos but i have a problem, if you can help me.

The problem is:

Failed to locate script /apps/components/header.html (500)

The requested URL /content/podcasts.html resulted in an error in /apps/components/podcasts/html.html.
Exception:

org.apache.sling.scripting.sightly.SightlyException: Failed to locate script /apps/components/header.html
	at org.apache.sling.scripting.sightly.impl.engine.extension.IncludeRuntimeExtension.includeScript(IncludeRuntimeExtension.java:114)
	at org.apache.sling.scripting.sightly.impl.engine.extension.IncludeRuntimeExtension.call(IncludeRuntimeExtension.java:71)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:69)
	at org.apache.sling.scripting.sightly.apps.components.podcasts.html_html.render(html_html.java:42)
	at org.apache.sling.scripting.sightly.java.compiler.RenderUnit.render(RenderUnit.java:48)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:61)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:72)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:128)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)

Request Progress:

      0 TIMER_START{Request Processing}
     13 COMMENT timer_end format is {<elapsed microseconds>,<timer name>} <optional message>
     23 LOG Method=GET, PathInfo=null
     32 TIMER_START{handleSecurity}
   3431 TIMER_END{3396,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@55a3b8 returns true
   4589 TIMER_START{ResourceResolution}
   4754 TIMER_END{163,ResourceResolution} URI=/content/podcasts.html resolves to Resource=JcrNodeResource, type=components/podcasts, superType=null, path=/content/podcasts
   4766 LOG Resource Path Info: SlingRequestPathInfo: path='/content/podcasts', selectorString='null', extension='html', suffix='null'
   4767 TIMER_START{ServletResolution}
   4772 TIMER_START{resolveServlet(/content/podcasts)}
   4796 TIMER_END{22,resolveServlet(/content/podcasts)} Using servlet /apps/components/podcasts/html.html
   4802 TIMER_END{34,ServletResolution} URI=/content/podcasts.html handled by Servlet=/apps/components/podcasts/html.html
   4808 LOG Applying Requestfilters
   4816 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   4824 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
   4829 LOG Applying Componentfilters
   4839 TIMER_START{/apps/components/podcasts/html.html#0}
   6555 LOG SCRIPT ERROR: Failed to locate script /apps/components/header.html
   6571 TIMER_END{1730,/apps/components/podcasts/html.html#0}
   6627 LOG Filter timing: filter=org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter, inner=2, total=2, outer=0
   7107 LOG Applying Error filters
   7119 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   7129 TIMER_START{handleError:throwable=org.apache.sling.scripting.sightly.SightlyException}
   7748 TIMER_END{617,handleError:throwable=org.apache.sling.scripting.sightly.SightlyException} Using handler org.apache.sling.servlets.resolver.internal.defaults.DefaultErrorHandlerServlet
   8560 TIMER_END{8558,Request Processing} Dumping SlingRequestProgressTracker Entries

ApacheSling/2.6 (jetty/9.3.15.v20161220, OpenJDK Server VM 1.8.0_131, Linux 4.4.0-93-generic i386)

**Comment by programmervsworld** [comment]
Hmm. I need to the see the html.html file. This typically just means the header.html file is missing from the /apps/components dir.
